FROM python:3.11-slim

WORKDIR /app

COPY scraper-service/requirements_scraping.txt .
RUN pip install --no-cache-dir -r requirements_scraping.txt
RUN playwright install chromium

COPY scraper-service/scripts/ ./scripts/
COPY scraper-service/scraper/ ./scraper/
COPY scraper-service/utils/ ./utils/
COPY scraper-service/api/ ./api/

EXPOSE 8000

CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000"]
